# Generated by Django 3.1.3 on 2020-11-18 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Subasta', '0003_auto_20201117_2053'),
        ('Oferta', '0002_auto_20201117_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='Subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subasta.subasta'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='Usuario_oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
