# Generated by Django 3.1.3 on 2020-11-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oferta', '0003_auto_20201117_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='Usuario_oferta',
        ),
    ]
