# Generated by Django 3.1.3 on 2020-11-18 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Oferta', '0004_remove_oferta_usuario_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='Usuario_oferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
