# Generated by Django 3.1.3 on 2020-11-17 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Producto', '0004_auto_20201117_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Vendedor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
