# Generated by Django 3.1.3 on 2020-11-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(blank=True, default='Espera', max_length=200)),
                ('Precio_Final', models.FloatField(blank=True, default=0)),
                ('Nombre_Producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Producto.producto')),
            ],
        ),
    ]
