# Generated by Django 3.1.3 on 2020-11-18 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subasta', '0003_auto_20201117_2053'),
        ('Oferta', '0006_auto_20201117_2205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Fecha',
        ),
        migrations.AddField(
            model_name='venta',
            name='Subasta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Subasta.subasta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Total',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Oferta.oferta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='Vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
