# Generated by Django 3.1.3 on 2020-11-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0002_auto_20201117_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='Promedio',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
