# Generated by Django 3.1.3 on 2020-11-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
