# Generated by Django 3.1.3 on 2020-11-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auto_20201118_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
