# Generated by Django 3.1.3 on 2020-11-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20201118_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
